import {test} from 'node:test';
import assert from 'node:assert/strict';
import {handle} from '../worker/handler.mjs';
import {accountRead,accountUpdate,hashPassword} from '../worker/accounts.mjs';
import worker from '../dist/server/index.js';
class Bucket{objects=new Map();async get(k){const o=this.objects.get(k);return o?{etag:o.etag,json:async()=>JSON.parse(o.body),body:o.body}:null;}async put(k,body,options={}){const old=this.objects.get(k);if(options.onlyIf?.etagMatches&&old?.etag!==options.onlyIf.etagMatches)return null;if(options.onlyIf?.etagDoesNotMatch==='*'&&old)return null;const etag=crypto.randomUUID();this.objects.set(k,{body,etag});return{etag};}async delete(k){this.objects.delete(k);}}
const make=()=>({BUCKET:new Bucket(),FIRST_ADMIN_EMAIL:'owner@example.test',ADMIN_EMAILS:'owner@example.test'});
const generated=()=>crypto.randomUUID()+'-'+crypto.randomUUID();
const origin='https://school.test';
async function call(env,path,method='GET',data,cookie='',owner=false,headers={}){return handle(new Request(origin+path,{method,headers:{origin,...(cookie?{cookie}:{}),...(owner?{'oai-authenticated-user-id':'verified-owner','oai-authenticated-user-email':'owner@example.test'}:{}),...headers},body:data===undefined?undefined:JSON.stringify(data)}),env);}
const cookieOf=r=>r.headers.get('set-cookie')?.split(';')[0];
async function setup(env){const password=generated(),r=await call(env,'/api/auth/setup','POST',{password},'',true);assert.equal(r.status,200);return {password,cookie:cookieOf(r),user:(await r.json()).user};}
test('first admin setup is bound to verified identity, stored without plaintext, one time, and not a demo role',async()=>{const e=make();assert.equal((await call(e,'/api/auth/setup','POST',{password:generated(),role:'admin'})).status,403);assert.equal((await call(e,'/api/admin/users','GET',undefined,'',true)).status,403);const {password,cookie,user}=await setup(e);assert.deepEqual(user.roles,['admin']);const {doc}=await accountRead(e);assert.ok(doc.users[0].password.hash);assert.ok(!JSON.stringify(doc).includes(password));assert.ok(!JSON.stringify(doc).includes(cookie.split('=')[1]));assert.equal((await call(e,'/api/auth/setup','POST',{password:generated()},'',true)).status,409);assert.equal((await call(e,'/api/admin/users','GET',undefined,cookie)).status,200);});
test('real password login and logout revoke server session even with owner headers; admin pages enforce permissions',async()=>{const e=make(),s=await setup(e);const wrong=await call(e,'/api/auth/login','POST',{email:s.user.email,password:generated()});assert.equal(wrong.status,401);const login=await call(e,'/api/auth/login','POST',{email:s.user.email,password:s.password});assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);const c=cookieOf(login);assert.equal((await worker.fetch(new Request(origin+'/admin',{headers:{cookie:c}}),e)).status,200);assert.equal((await worker.fetch(new Request(origin+'/admin'),e)).status,303);assert.equal((await call(e,'/api/auth/logout','POST',undefined,c)).status,200);assert.equal((await call(e,'/api/admin/users','GET',undefined,c,true)).status,403);assert.equal((await call(e,'/api/session','GET',undefined,c,true).then(r=>r.json())).role,'visitor');});
test('owner recovery resets password, closes old sessions, and rejects unverified callers',async()=>{const e=make(),s=await setup(e),password=generated();assert.equal((await call(e,'/api/auth/recover-owner','POST',{password})).status,403);const r=await call(e,'/api/auth/recover-owner','POST',{password},'',true);assert.equal(r.status,200);assert.equal((await call(e,'/api/admin/users','GET',undefined,s.cookie)).status,403);assert.equal((await call(e,'/api/auth/login','POST',{email:s.user.email,password:s.password})).status,401);assert.equal((await call(e,'/api/auth/login','POST',{email:s.user.email,password})).status,200);assert.equal((await call(e,'/api/auth/reset-request','POST',{email:s.user.email})).status,503);});
test('non-admin cannot read/write admin records or promote themselves',async()=>{const e=make(),s=await setup(e);const created=await call(e,'/api/admin/users','POST',{name:'Student',email:'student@example.test',roles:['student']},s.cookie);assert.equal(created.status,201);const u=(await created.json()).user,password=generated();await accountUpdate(e,d=>{const x=d.users.find(x=>x.id===u.id);x.status='active';});const h=await hashPassword(password);await accountUpdate(e,d=>{d.users.find(x=>x.id===u.id).password=h;});const l=await call(e,'/api/auth/login','POST',{email:u.email,password}),c=cookieOf(l);assert.equal(l.status,200);for(const [p,m,b]of [['/api/admin/users','GET'],['/api/admin/school','GET'],['/api/manage','GET'],['/api/site','PUT',{}],['/api/admin/users/'+u.id,'PATCH',{roles:['admin']}],['/api/admin/school/courses','POST',{record:{}}]])assert.equal((await call(e,p,m,b,c)).status,403);assert.equal((await worker.fetch(new Request(origin+'/admin',{headers:{cookie:c}}),e)).status,403);assert.equal((await call(e,'/api/auth/register','POST',{email:'bad@example.test',name:'Bad',role:'admin'})).status,400);});
test('admin records persist; references, parent links, course periods and stale writes are validated',async()=>{const e=make(),s=await setup(e);const add=async(role,name)=>{const r=await call(e,'/api/admin/users','POST',{name,email:name+'@example.test',roles:[role]},s.cookie);return (await r.json()).user;};const student=await add('student','student'),parent=await add('parent','parent'),teacher=await add('teacher','teacher');let etag=null;const put=async(kind,record)=>{const r=await call(e,'/api/admin/school/'+kind,'POST',{record,etag},s.cookie),b=await r.json();if(r.ok)etag=b.etag;return {r,b};};const pair={en:'Course',th:''};const {r,b}=await put('courses',{title:pair,description:pair,subject:'Science',level:'Primary',language:'en',teacherIds:[teacher.id],status:'published',lessons:[]});assert.equal(r.status,201);const id=b.record.id;assert.equal((await put('assignments',{student:student.id,course:id,mode:'duration',starts:new Date().toISOString(),days:30,active:true})).r.status,201);assert.equal((await put('links',{parent:parent.id,student:student.id,verified:false,active:true,verificationNote:'School verified'})).r.status,400);assert.equal((await put('links',{parent:parent.id,student:student.id,verified:true,active:true,verificationNote:'School verified'})).r.status,201);const view=await(await call(e,'/api/admin/school','GET',undefined,s.cookie)).json();assert.equal(view.courses.length,1);assert.equal(view.assignments.length,1);assert.equal(view.links[0].verifiedBy,s.user.id);assert.equal((await call(e,'/api/admin/school/events','POST',{etag:null,record:{}},s.cookie)).status,409);assert.equal((await call(e,'/api/learning')).status,401);});
test('unsafe origins are rejected and repeated login attempts are throttled',async()=>{const e=make();assert.equal((await call(e,'/api/auth/login','POST',{email:'none@example.test',password:'short'},'',false,{origin:'https://evil.test'})).status,403);for(let i=0;i<8;i++)assert.equal((await call(e,'/api/auth/login','POST',{email:'none@example.test',password:'short'})).status,401);assert.equal((await call(e,'/api/auth/login','POST',{email:'none@example.test',password:'short'})).status,429);});
test('one-time invitation and reset tokens are hashed, expire, cannot be reused, and revoke sessions',async()=>{const e=make(),s=await setup(e);e.RESEND_API_KEY='test-only-provider-key';e.EMAIL_FROM='School <school@example.test>';const original=globalThis.fetch;let captured;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');captured=JSON.parse(options.body);return new Response('{}',{status:200});};try{let r=await call(e,'/api/admin/users','POST',{name:'Parent',email:'parent@example.test',roles:['parent']},s.cookie);const u=(await r.json()).user;assert.equal((await call(e,'/api/admin/users/'+u.id+'/invite','POST',{},s.cookie)).status,200);const token=captured.text.match(/token=([a-f0-9]+)/)[1];assert.ok(!JSON.stringify((await accountRead(e)).doc).includes(token));const p=generated();assert.equal((await call(e,'/api/auth/set-password','POST',{token,password:p})).status,200);assert.equal((await call(e,'/api/auth/set-password','POST',{token,password:p})).status,400);r=await call(e,'/api/auth/login','POST',{email:u.email,password:p});const oldCookie=cookieOf(r);assert.equal(r.status,200);assert.equal((await call(e,'/api/auth/reset-request','POST',{email:u.email})).status,200);const reset=captured.text.match(/token=([a-f0-9]+)/)[1];assert.equal((await call(e,'/api/auth/set-password','POST',{token:reset,password:generated()})).status,200);assert.equal((await call(e,'/api/session','GET',undefined,oldCookie).then(r=>r.json())).role,'visitor');await call(e,'/api/auth/reset-request','POST',{email:u.email});const expired=captured.text.match(/token=([a-f0-9]+)/)[1];await accountUpdate(e,d=>{d.tokens.forEach(t=>t.expires=0);});assert.equal((await call(e,'/api/auth/set-password','POST',{token:expired,password:generated()})).status,400);assert.equal((await call(e,'/api/auth/register','POST',{email:'intruder@example.test',name:'Intruder',role:'student',roles:['admin']})).status,403);}finally{globalThis.fetch=original;}});
