import {test} from 'node:test';import assert from 'node:assert/strict';import {handle} from '../worker/handler.mjs';
class Bucket{objects=new Map();async get(k){const o=this.objects.get(k);if(!o)return null;return {etag:o.etag,json:async()=>JSON.parse(o.body),body:o.body}}async put(k,body,options={}){const old=this.objects.get(k);if(options.onlyIf?.etagMatches&&old?.etag!==options.onlyIf.etagMatches)return null;if(options.onlyIf?.etagDoesNotMatch==='*'&&old)return null;const etag=crypto.randomUUID();this.objects.set(k,{body,etag});return {etag}}async delete(k){this.objects.delete(k)}}
const env=()=>({BUCKET:new Bucket(),ADMIN_EMAILS:'admin@example.test',TEACHER_ASSIGNMENTS:JSON.stringify({'teacher@example.test':['science']})});
const call=async(e,path,method='GET',body,who='admin',extra={})=>{const headers={...extra};if(who){headers['oai-authenticated-user-id']=who;headers['oai-authenticated-user-email']=who+'@example.test'}if(method!=='GET')headers.origin='https://school.test';let data=body;if(body&&!(body instanceof Uint8Array)){headers['content-type']='application/json';data=JSON.stringify(body)}return handle(new Request('https://school.test'+path,{method,headers,body:data}),e)};
const png=()=>{const b=new Uint8Array(24);b.set([137,80,78,71,13,10,26,10]);b.set([73,72,68,82],12);new DataView(b.buffer).setUint32(16,10);new DataView(b.buffer).setUint32(20,10);return b};
test('management is fail-closed for anonymous and demo roles',async()=>{const e=env();for(const role of [null,'student','parent'])assert.equal((await call(e,'/api/manage','GET',null,role)).status,403);e.ADMIN_EMAILS='';assert.equal((await call(e,'/api/manage')).status,403)});
test('appearance persists, rejects stale writes, and enforces contrast',async()=>{const e=env(),d=await(await call(e,'/api/manage')).json();const a={...d.appearance,accent:'#e0f291'};let r=await call(e,'/api/site','PUT',{etag:d.etag,appearance:a});assert.equal(r.status,200);assert.equal((await(await call(e,'/api/site','GET',null,null)).json()).appearance.accent,'#e0f291');assert.equal((await call(e,'/api/site','PUT',{etag:d.etag,appearance:a})).status,409);const n=await(await call(e,'/api/manage')).json();assert.equal((await call(e,'/api/site','PUT',{etag:n.etag,appearance:{...a,text:'#ffffff'}})).status,400)});
test('teacher upload is limited to assigned private courses',async()=>{const e=env();for(const scope of ['public','course:physics'])assert.equal((await call(e,'/api/upload','POST',png(),'teacher',{'content-type':'image/png','X-Media-Scope':scope})).status,403);const response=await call(e,'/api/upload','POST',png(),'teacher',{'content-type':'image/png','X-Media-Scope':'course:science'});assert.equal(response.status,201);const{id}=await response.json();assert.equal((await call(e,'/api/media/'+id,'GET',null,null)).status,403);assert.equal((await call(e,'/api/media/'+id,'GET',null,'student')).status,403);assert.equal((await call(e,'/api/media/'+id,'GET',null,'teacher')).status,200)});
test('rejects invalid image signatures and over-size payloads',async()=>{const e=env();assert.equal((await call(e,'/api/upload','POST',new Uint8Array([1,2,3]),'admin',{'content-type':'image/png','X-Media-Scope':'public'})).status,400);assert.equal((await call(e,'/api/upload','POST',new Uint8Array(5*1024*1024+1),'admin',{'content-type':'image/png','X-Media-Scope':'public'})).status,413)});
test('public media requires English alt text; in-use media cannot be deleted',async()=>{const e=env();const{id}=await(await call(e,'/api/upload','POST',png(),'admin',{'content-type':'image/png','X-Media-Scope':'public'})).json();let d=await(await call(e,'/api/manage')).json();const c={home:{title:{en:'School',th:''},description:{en:'Welcome',th:''},image:id}};assert.equal((await call(e,'/api/site','PUT',{etag:d.etag,content:c})).status,400);assert.equal((await call(e,'/api/media/'+id,'PATCH',{alt:{en:'Science experiment',th:''},caption:{en:'',th:''},focal:{x:30,y:70}})).status,200);d=await(await call(e,'/api/manage')).json();assert.equal((await call(e,'/api/site','PUT',{etag:d.etag,content:c})).status,200);assert.equal((await call(e,'/api/media/'+id,'DELETE')).status,409);assert.equal((await call(e,'/api/media/'+id,'GET',null,null)).status,200);const p=await(await call(e,'/api/site','GET',null,null)).json();assert.equal(p.content.home.title.en,'School');assert.equal(p.media[0].key,undefined)});
test('mutations reject cross-origin requests',async()=>{const r=await handle(new Request('https://school.test/api/site',{method:'PUT',headers:{origin:'https://evil.test','oai-authenticated-user-id':'admin','oai-authenticated-user-email':'admin@example.test'},body:'{}'}),env());assert.equal(r.status,403)});
