import { scryptAsync } from '@noble/hashes/scrypt.js';

const KEY='private-system/accounts-v1.json';
const COOKIE='__Host-hs_session';
const now=()=>Date.now();
const bad=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');
const random=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
const digest=async text=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))));
const emailOf=x=>typeof x==='string'?x.trim().toLowerCase():'';
const emailValid=x=>x.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x);
const ROLES=['admin','teacher','student','parent'];
export const accountError=bad;
export async function accountRead(env){if(!env.BUCKET)bad('unavailable',503);const o=await env.BUCKET.get(KEY);return o?{doc:await o.json(),etag:o.etag}:{doc:{users:[],sessions:[],tokens:[],rates:{},audit:[]},etag:null};}
export async function accountUpdate(env,fn){for(let i=0;i<8;i++){const{doc,etag}=await accountRead(env);const result=fn(doc);const saved=await env.BUCKET.put(KEY,JSON.stringify(doc),{onlyIf:etag?{etagMatches:etag}:{etagDoesNotMatch:'*'},httpMetadata:{contentType:'application/json'}});if(saved)return result;}bad('conflict',409);}
function log(d,actor,action,target){d.audit.push({at:new Date().toISOString(),actor,action,target});d.audit=d.audit.slice(-1000);}
export function safeUser(u){return {id:u.id,email:u.email,name:u.name,roles:u.roles,status:u.status,created:u.created,profile:u.profile||{}};}
function passwordValid(p){if(typeof p!=='string'||p.length<15||p.length>128)bad('password_length');}
export async function hashPassword(p,salt=random()){passwordValid(p);const bytes=await scryptAsync(new TextEncoder().encode(p),new TextEncoder().encode(salt),{N:16384,r:8,p:5,dkLen:32,maxmem:64*1024*1024,asyncTick:10});return {scheme:'scrypt-v1',salt,hash:hex(bytes)};}
function equal(a,b){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
async function verifyPassword(p,stored){if(typeof p!=='string'||p.length<15||p.length>128)return false;const result=await hashPassword(p,stored?.salt||'0000000000000000000000000000000000000000000000000000000000000000');return !!stored&&stored.scheme==='scrypt-v1'&&equal(result.hash,stored.hash);}
function sessionToken(req){return (req.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(COOKIE+'='))?.slice(COOKIE.length+1)||'';}
export async function schoolIdentity(req,env){const token=sessionToken(req);if(!/^[a-f0-9]{64}$/.test(token))return {role:'visitor',roles:[],courses:[]};const{doc}=await accountRead(env),h=await digest(token),s=doc.sessions.find(s=>s.hash===h&&s.expires>now()),u=s&&doc.users.find(u=>u.id===s.user&&u.status==='active'&&u.version===s.version);return u?{...safeUser(u),role:ROLES.find(r=>u.roles.includes(r)),courses:[],school:true}:{role:'visitor',roles:[],courses:[]};}
function bootstrapIdentity(req,env){const id=req.headers.get('oai-authenticated-user-id'),email=emailOf(req.headers.get('oai-authenticated-user-email'));return id&&email&&email===emailOf(env.FIRST_ADMIN_EMAIL)?{id,email}:null;}
async function throttle(req,env,kind,email=''){const ip=req.headers.get('cf-connecting-ip')||'unavailable';const keys=await Promise.all([digest(kind+':ip:'+ip),digest(kind+':account:'+email)]);await accountUpdate(env,d=>{const time=now();for(const [k,v]of Object.entries(d.rates))if(v.until<time)delete d.rates[k];for(const [i,key]of keys.entries()){const x=d.rates[key]||{count:0,until:time+15*60*1000};if(x.count>=(i===0?30:8))bad('rate_limit',429);x.count++;d.rates[key]=x;}if(Object.keys(d.rates).length>10000)bad('rate_limit',429);});}
function cookie(token,clear=false){return `${COOKIE}=${clear?'':token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${clear?0:28800}`;}
function response(data,status=200,token){const headers={'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};if(token!==undefined)headers['Set-Cookie']=cookie(token,token==='');return new Response(JSON.stringify(data),{status,headers});}
async function createSession(env,userId,version,expectedPassword){const token=random(),hash=await digest(token);await accountUpdate(env,d=>{const u=d.users.find(u=>u.id===userId);if(!u||u.status!=='active'||u.version!==version||(expectedPassword&&u.password?.hash!==expectedPassword))bad('invalid_login',401);d.sessions=d.sessions.filter(s=>s.expires>now()).slice(-4999);d.sessions.push({hash,user:u.id,version:u.version,expires:now()+8*60*60*1000});log(d,u.id,'login',u.id);});return token;}
export const emailReady=env=>!!env.RESEND_API_KEY&&!!env.EMAIL_FROM;
async function sendLink(env,to,url,kind){if(!emailReady(env))bad('email_not_configured',503);const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+env.RESEND_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:env.EMAIL_FROM,to:[to],subject:kind==='reset'?'Headstart Academics — reset your password':'Headstart Academics — set your password',text:`Open this one-time link to ${kind==='reset'?'reset':'set'} your Headstart Academics password:\n\n${url}\n\nThis link expires in 30 minutes. If you did not request it, ignore this email.`})});if(!r.ok)bad('email_delivery_failed',502);}
async function issueToken(env,user,kind){const token=random(),hash=await digest(token);await accountUpdate(env,d=>{if(!d.users.some(u=>u.id===user.id&&u.status!=='disabled'))bad('not_found',404);d.tokens=d.tokens.filter(t=>t.expires>now()&&!(t.user===user.id&&t.kind===kind));d.tokens.push({hash,user:user.id,kind,expires:now()+30*60*1000});});return token;}
export async function authEndpoint(req,env,path,readBody){if(!path.startsWith('/api/auth/'))return null;const first=bootstrapIdentity(req,env);
if(path==='/api/auth/status'&&req.method==='GET'){const{doc}=await accountRead(env),u=first&&doc.users.find(u=>u.email===first.email);return response({emailDelivery:emailReady(env),setupAllowed:!!first&&!doc.users.some(u=>u.roles.includes('admin')),recoveryAllowed:!!first&&!!u&&u.platformId===first.id&&u.status==='active',setupEmail:first?.email||null});}
if(req.method!=='POST')bad('not_found',404);
if(path==='/api/auth/logout'){const hash=await digest(sessionToken(req));await accountUpdate(env,d=>{d.sessions=d.sessions.filter(s=>s.hash!==hash);});return response({ok:true},200,'');}
const data=await readBody(req),email=emailOf(data.email);
if(path==='/api/auth/setup'||path==='/api/auth/recover-owner'){if(!first)bad('forbidden',403);await throttle(req,env,'setup',first.email);const password=await hashPassword(data.password);const user=await accountUpdate(env,d=>{let u=d.users.find(u=>u.email===first.email);if(path.endsWith('/setup')){if(d.users.some(u=>u.roles.includes('admin')))bad('setup_closed',409);if(u)bad('setup_closed',409);u={id:crypto.randomUUID(),email:first.email,name:'School Administrator',roles:['admin'],status:'active',created:new Date().toISOString(),version:1,password,platformId:first.id};d.users.push(u);log(d,u.id,'initial-administrator-created',u.id);}else{if(!u||u.platformId!==first.id||u.status!=='active')bad('forbidden',403);u.password=password;u.version++;d.sessions=d.sessions.filter(s=>s.user!==u.id);d.tokens=d.tokens.filter(t=>t.user!==u.id);log(d,u.id,'owner-password-recovery',u.id);}return structuredClone(u);});const token=await createSession(env,user.id,user.version);return response({user:safeUser(user)},200,token);}
if(path==='/api/auth/login'){if(!emailValid(email))bad('invalid_login',401);await throttle(req,env,'login',email);const{doc}=await accountRead(env),u=doc.users.find(u=>u.email===email);const valid=await verifyPassword(data.password,u?.password);if(!valid||u.status!=='active')bad('invalid_login',401);const token=await createSession(env,u.id,u.version,u.password.hash);return response({user:safeUser(u)},200,token);}
if(path==='/api/auth/reset-request'){if(!emailValid(email))bad('invalid');if(!emailReady(env))bad('email_not_configured',503);await throttle(req,env,'reset',email);const{doc}=await accountRead(env),u=doc.users.find(u=>u.email===email&&u.status==='active');if(u){const token=await issueToken(env,u,'reset');try{await sendLink(env,u.email,new URL('/#set-password?token='+token,req.url).href,'reset');}catch{await accountUpdate(env,d=>{d.tokens=d.tokens.filter(t=>t.user!==u.id||t.kind!=='reset');});/* Generic outcome prevents account enumeration. */}}return response({accepted:true});}
if(path==='/api/auth/set-password'){if(!/^[a-f0-9]{64}$/.test(data.token||''))bad('invalid_token');await throttle(req,env,'redeem');const hash=await digest(data.token);const{doc}=await accountRead(env);if(!doc.tokens.some(t=>t.hash===hash&&t.expires>now()))bad('invalid_token');const password=await hashPassword(data.password);const user=await accountUpdate(env,d=>{const token=d.tokens.find(t=>t.hash===hash&&t.expires>now()),u=token&&d.users.find(u=>u.id===token.user&&u.status!=='disabled');if(!u)bad('invalid_token');u.password=password;u.version++;u.status='active';d.tokens=d.tokens.filter(t=>t.user!==u.id);d.sessions=d.sessions.filter(s=>s.user!==u.id);log(d,u.id,'password-set',u.id);return structuredClone(u);});return response({ok:true});}
if(path==='/api/auth/register'){if(!emailValid(email)||!['student','parent'].includes(data.role)||typeof data.name!=='string'||!data.name.trim()||data.name.length>160)bad('invalid');if(data.roles||data.permissions)bad('forbidden',403);if(!emailReady(env))bad('email_not_configured',503);await throttle(req,env,'register',email);const user=await accountUpdate(env,d=>{if(d.users.some(u=>u.email===email))return null;if(d.users.length>=5000)bad('limit',409);const u={id:crypto.randomUUID(),email,name:data.name.trim(),roles:[data.role],status:'invited',version:1,created:new Date().toISOString()};d.users.push(u);return u;});if(user){const token=await issueToken(env,user,'invite');try{await sendLink(env,user.email,new URL('/#set-password?token='+token,req.url).href,'invite');}catch{}}return response({accepted:true});}
bad('not_found',404);}

export async function adminAccounts(req,env,user,path,readBody){if(!path.startsWith('/api/admin/users')&&path!=='/api/admin/audit')return null;if(!user.roles?.includes('admin'))bad('forbidden',403);
if(path==='/api/admin/audit'&&req.method==='GET'){const{doc}=await accountRead(env);return response({audit:doc.audit.slice(-100).reverse()});}
if(path==='/api/admin/users'&&req.method==='GET'){const{doc}=await accountRead(env);return response({users:doc.users.map(safeUser)});}
const data=await readBody(req);
if(path==='/api/admin/users'&&req.method==='POST'){const email=emailOf(data.email),roles=data.roles;if(!emailValid(email)||typeof data.name!=='string'||!data.name.trim()||data.name.length>160||!Array.isArray(roles)||!roles.length||roles.some(r=>!ROLES.includes(r)))bad('invalid');const u=await accountUpdate(env,d=>{if(d.users.some(u=>u.email===email))bad('email_exists',409);if(d.users.length>=5000)bad('limit',409);const u={id:crypto.randomUUID(),name:data.name.trim(),email,roles:[...new Set(roles)],status:'invited',version:1,created:new Date().toISOString()};d.users.push(u);log(d,user.id,'user-created',u.id);return u;});return response({user:safeUser(u)},201);}
const match=path.match(/^\/api\/admin\/users\/([a-f0-9-]{36})(\/invite)?$/);if(!match)bad('not_found',404);
if(match[2]&&req.method==='POST'){const{doc}=await accountRead(env),u=doc.users.find(u=>u.id===match[1]&&u.status==='invited');if(!u)bad('not_found',404);if(!emailReady(env))bad('email_not_configured',503);const token=await issueToken(env,u,'invite');await sendLink(env,u.email,new URL('/#set-password?token='+token,req.url).href,'invite');return response({sent:true});}
if(req.method==='PATCH'){const u=await accountUpdate(env,d=>{const u=d.users.find(u=>u.id===match[1]);if(!u)bad('not_found',404);if(!Array.isArray(data.roles)||!data.roles.length||data.roles.some(r=>!ROLES.includes(r))||!['active','disabled','invited'].includes(data.status)||typeof data.name!=='string'||!data.name.trim()||data.name.length>160)bad('invalid');if(u.id===user.id&&(!data.roles.includes('admin')||data.status!=='active'))bad('own_access');if(u.status==='invited'&&data.status==='active'&&!u.password)bad('password_not_set');if(u.roles.includes('admin')&&(!data.roles.includes('admin')||data.status!=='active')&&!d.users.some(x=>x.id!==u.id&&x.roles.includes('admin')&&x.status==='active'))bad('last_admin');u.name=data.name.trim();u.roles=[...new Set(data.roles)];u.status=data.status;u.version++;d.sessions=d.sessions.filter(s=>s.user!==u.id);log(d,user.id,'user-permissions-updated',u.id);return u;});return response({user:safeUser(u)});}
bad('not_found',404);}
