import {schoolIdentity,authEndpoint,adminAccounts} from './accounts.mjs';
import {schoolEndpoint,courseIdsFor} from './school.mjs';
const DOC_KEY='system/site-v2.json';
const MAX=5*1024*1024;
const fail=(code,status=400)=>{throw Object.assign(new Error(code),{status})};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const defaults={primary:'#152238',secondary:'#637080',accent:'#d2ee7b',background:'#ffffff',text:'#152238',logo:null,mobileLogo:null,footerLogo:null,favicon:null};
function identity(req,env){const id=req.headers.get('oai-authenticated-user-id'),email=(req.headers.get('oai-authenticated-user-email')||'').trim().toLowerCase();if(!id||!email)return {role:'visitor',courses:[]};const admins=(env.ADMIN_EMAILS||'').split(',').map(s=>s.trim().toLowerCase()).filter(Boolean);if(admins.includes(email))return {id,role:'admin',courses:[]};let teachers={};try{teachers=JSON.parse(env.TEACHER_ASSIGNMENTS||'{}')}catch{}const courses=Array.isArray(teachers[email])?teachers[email].filter(c=>['science','physics','chemistry'].includes(c)):[];return {id,role:courses.length?'teacher':'visitor',courses}}
const canScope=(u,scope)=>u.role==='admin'||(u.role==='teacher'&&scope.startsWith('course:')&&u.courses.includes(scope.slice(7)));
async function read(env){if(!env.BUCKET)fail('unavailable',503);const object=await env.BUCKET.get(DOC_KEY);return object?{doc:await object.json(),etag:object.etag}:{doc:{appearance:{...defaults},draftAppearance:null,content:{},media:[]},etag:null}}
async function write(env,doc,etag){const saved=await env.BUCKET.put(DOC_KEY,JSON.stringify(doc),{onlyIf:etag?{etagMatches:etag}:{etagDoesNotMatch:'*'},httpMetadata:{contentType:'application/json'}});if(!saved)fail('conflict',409);return saved.etag}
function auth(u,role='admin'){if(role==='admin'?u.role!=='admin':!['admin','teacher'].includes(u.role))fail('forbidden',403)}
function pair(v,required=false,max=6000){if(!v||typeof v.en!=='string'||typeof v.th!=='string'||v.en.length>max||v.th.length>max||(required&&!v.en.trim()))fail('invalid');return {en:v.en,th:v.th}}
function refs(doc,id,publishedOnly=false){const list=[];for(const [key,c]of Object.entries(doc.content))if(c.image===id)list.push('content:'+key);for(const [k,v]of Object.entries(doc.appearance))if(v===id)list.push('appearance:'+k);if(!publishedOnly)for(const[k,v]of Object.entries(doc.draftAppearance||{}))if(v===id)list.push('draft:'+k);return list}
function checkImageRef(doc,id,requireAlt=true){if(id===null)return;const m=doc.media.find(m=>m.id===id);if(!m||m.scope!=='public'||(requireAlt&&!m.alt.en.trim()))fail('invalid');}
function ratio(a,b){const lum=c=>{const a=c.match(/[a-f\d]{2}/gi).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722};const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}
function appearance(v,doc,publish){if(!v||typeof v!=='object')fail('invalid');const a={};for(const k of ['primary','secondary','accent','background','text']){if(!/^#[0-9a-f]{6}$/i.test(v[k]))fail('invalid');a[k]=v[k]}for(const k of ['logo','mobileLogo','footerLogo','favicon']){if(v[k]!==null&&typeof v[k]!=='string')fail('invalid');checkImageRef(doc,v[k],publish);a[k]=v[k]}if(publish&&[[a.text,a.background],[a.secondary,a.background],[a.primary,a.accent]].some(([x,y])=>ratio(x,y)<4.5))fail('contrast');return a}
async function limitedBody(req,max){const reader=req.body?.getReader();if(!reader)return new Uint8Array();let length=0,parts=[];while(true){const{done,value}=await reader.read();if(done)break;length+=value.length;if(length>max){await reader.cancel();fail('invalid_image',413)}parts.push(value)}const all=new Uint8Array(length);let pos=0;for(const p of parts){all.set(p,pos);pos+=p.length}return all}
async function bodyJSON(req){const bytes=await limitedBody(req,150000);try{return JSON.parse(new TextDecoder().decode(bytes))}catch{fail('invalid')}}
function imageInfo(bytes,type){const b=bytes,d=new DataView(b.buffer,b.byteOffset,b.byteLength);let width=0,height=0;const ascii=(start,end)=>String.fromCharCode(...b.slice(start,end));try{if(type==='image/png'&&b.length>=24&&b[0]===137&&ascii(1,4)==='PNG'&&ascii(12,16)==='IHDR'){width=d.getUint32(16);height=d.getUint32(20)}else if(type==='image/jpeg'&&b[0]===255&&b[1]===216){let p=2;while(p<b.length-9){if(b[p++]!==255)continue;const marker=b[p++];if(marker===216||marker===217)continue;const len=d.getUint16(p);if(len<2)break;if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker)){height=d.getUint16(p+3);width=d.getUint16(p+5);break}p+=len}}else if(type==='image/webp'&&ascii(0,4)==='RIFF'&&ascii(8,12)==='WEBP'){const kind=ascii(12,16);if(kind==='VP8X'&&b.length>=30){width=1+b[24]+(b[25]<<8)+(b[26]<<16);height=1+b[27]+(b[28]<<8)+(b[29]<<16)}else if(kind==='VP8L'&&b[20]===47){const bits=d.getUint32(21,true);width=(bits&16383)+1;height=((bits>>>14)&16383)+1}else if(kind==='VP8 '&&b[23]===157&&b[24]===1&&b[25]===42){width=d.getUint16(26,true)&16383;height=d.getUint16(28,true)&16383}}}catch{fail('invalid_image')}if(!width||!height||width*height>40000000||width>2400||height>2400)fail('invalid_image');return {width,height}}
function publicDoc(doc){const media=doc.media.filter(m=>m.scope==='public'&&refs(doc,m.id,true).length).map(({key,...m})=>m);return {appearance:doc.appearance,content:doc.content,media}}
export async function protectedIdentity(req,env){const u=env.FIRST_ADMIN_EMAIL?await schoolIdentity(req,env):identity(req,env);if(env.FIRST_ADMIN_EMAIL&&u.role==='teacher')u.courses=await courseIdsFor(env,u);return u;}
export async function handle(req,env){const url=new URL(req.url),path=url.pathname;try{
if(!['GET','HEAD'].includes(req.method)){const origin=req.headers.get('origin');if(origin!==url.origin)fail('forbidden',403);const fetchSite=req.headers.get('sec-fetch-site');if(fetchSite&&fetchSite!=='same-origin')fail('forbidden',403)}
if(env.FIRST_ADMIN_EMAIL){const authResult=await authEndpoint(req,env,path,bodyJSON);if(authResult)return authResult;}
const user=await protectedIdentity(req,env);
if(path==='/api/session'&&req.method==='GET')return json({role:user.role,roles:user.roles||[user.role],courses:user.courses,id:user.id,name:user.name,email:user.email,school:!!user.school});
if(env.FIRST_ADMIN_EMAIL){const accountResult=await adminAccounts(req,env,user,path,bodyJSON);if(accountResult)return accountResult;const schoolResult=await schoolEndpoint(req,env,user,path,bodyJSON);if(schoolResult)return schoolResult;}
if(path==='/api/site'&&req.method==='GET'){const{doc}=await read(env);return json(publicDoc(doc))}
if(path==='/api/manage'&&req.method==='GET'){auth(user,'editor');const{doc,etag}=await read(env);const visible=doc.media.filter(m=>canScope(user,m.scope)).map(({key,...m})=>m);return json(user.role==='admin'?{...doc,media:visible,etag}:{media:visible,etag})}
if(path==='/api/site'&&req.method==='PUT'){auth(user);const input=await bodyJSON(req),{doc,etag}=await read(env);if(input.etag!==etag)fail('conflict',409);if(input.content){if(typeof input.content!=='object'||Array.isArray(input.content))fail('invalid');const allowed=['home','about','teacher','science','physics','chemistry','lesson','article','event','gallery'];for(const[id,value]of Object.entries(input.content)){if(!allowed.includes(id)||!value||typeof value!=='object')fail('invalid');const c={title:pair(value.title,true,200),description:pair(value.description,true),image:value.image??null};checkImageRef(doc,c.image);if(['science','physics','chemistry'].includes(id)){if(!['en','th','both'].includes(value.language))fail('invalid');c.language=value.language}doc.content[id]=c}}
if(input.draftAppearance)doc.draftAppearance=appearance(input.draftAppearance,doc,false);if(input.appearance)doc.appearance=appearance(input.appearance,doc,true);return json({etag:await write(env,doc,etag)})}
if(path==='/api/upload'&&req.method==='POST'){auth(user,'editor');const scope=req.headers.get('X-Media-Scope')||'';if(!(scope==='public'||/^course:[a-z0-9-]{1,64}$/.test(scope))||!canScope(user,scope))fail('forbidden',403);const type=(req.headers.get('content-type')||'').split(';')[0];if(!['image/png','image/jpeg','image/webp'].includes(type))fail('invalid_image');const bytes=await limitedBody(req,MAX);if(!bytes.length)fail('invalid_image');const dimensions=imageInfo(bytes,type),{doc,etag}=await read(env);if(doc.media.length>=200)fail('limit',409);const replace=req.headers.get('X-Replace-Id'),old=replace?doc.media.find(m=>m.id===replace):null;if(replace&&(!old||!canScope(user,old.scope)||old.scope!==scope))fail('forbidden',403);let name='image';try{name=decodeURIComponent(req.headers.get('X-Media-Name')||'image').slice(0,150)}catch{fail('invalid')}const id=old?.id||crypto.randomUUID(),version=crypto.randomUUID(),key=(scope==='public'?'public/':'private/'+scope.slice(7)+'/')+id+'/'+version;await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:type}});const m={id,key,version,name,scope,type,size:bytes.length,...dimensions,alt:old?.alt||{en:'',th:''},caption:old?.caption||{en:'',th:''},focal:old?.focal||{x:50,y:50},owner:user.id};if(old)doc.media[doc.media.findIndex(m=>m.id===id)]=m;else doc.media.push(m);try{await write(env,doc,etag)}catch(e){await env.BUCKET.delete(key);throw e}if(old)await env.BUCKET.delete(old.key);return json({id},201)}
const match=path.match(/^\/api\/media\/([a-f0-9-]{36})$/);if(match){const{doc,etag}=await read(env),id=match[1],m=doc.media.find(m=>m.id===id);if(!m)fail('not_found',404);if(req.method==='GET'||req.method==='HEAD'){if(m.scope==='public'){if(!refs(doc,id,true).length&&user.role!=='admin')fail('forbidden',403)}else if(!canScope(user,m.scope))fail('forbidden',403);const object=await env.BUCKET.get(m.key);if(!object)fail('not_found',404);return new Response(req.method==='HEAD'?null:object.body,{headers:{'Content-Type':m.type,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox",'Content-Disposition':'inline'}})}auth(user,'editor');if(!canScope(user,m.scope))fail('forbidden',403);if(req.method==='PATCH'){const data=await bodyJSON(req);m.alt=pair(data.alt,true,200);m.caption=pair(data.caption,false,200);if(!Number.isFinite(data.focal?.x)||!Number.isFinite(data.focal?.y)||data.focal.x<0||data.focal.x>100||data.focal.y<0||data.focal.y>100)fail('invalid');m.focal=data.focal;await write(env,doc,etag);return json({ok:true})}if(req.method==='DELETE'){const used=refs(doc,id);if(used.length)return json({error:'in_use',used},409);doc.media=doc.media.filter(m=>m.id!==id);await write(env,doc,etag);await env.BUCKET.delete(m.key);return json({ok:true})}}
return json({error:'not_found'},404);
}catch(e){if(!e.status)console.error('Headstart API failure',e.message);return json({error:e.status?e.message:'unavailable'},e.status||503)}}
