import {accountRead,accountError as reject} from './accounts.mjs';
const KEY='private-system/school-v1.json';
const collections=['courses','assignments','links','assessments','events','registrations'];
export async function schoolRead(env){const o=await env.BUCKET.get(KEY);return o?{doc:await o.json(),etag:o.etag}:{doc:{courses:[],assignments:[],links:[],assessments:[],events:[],registrations:[],progress:[],submissions:[]},etag:null};}
async function update(env,fn,expected){for(let i=0;i<8;i++){const{doc,etag}=await schoolRead(env);if(expected!==undefined&&expected!==etag)reject('conflict',409);const result=fn(doc);const saved=await env.BUCKET.put(KEY,JSON.stringify(doc),{onlyIf:etag?{etagMatches:etag}:{etagDoesNotMatch:'*'},httpMetadata:{contentType:'application/json'}});if(saved)return {result,etag:saved.etag};}reject('conflict',409);}
const out=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const text=(v,max=6000,required=false)=>{if(typeof v!=='string'||v.length>max||(required&&!v.trim()))reject('invalid');return v.trim();};
const bilingual=(v,required=true,max=6000)=>({en:text(v?.en,max,required),th:text(v?.th||'',max)});
const choice=(v,values)=>{if(!values.includes(v))reject('invalid');return v;};
const number=(v,min,max)=>{if(!Number.isInteger(v)||v<min||v>max)reject('invalid');return v;};
const date=v=>{if(typeof v!=='string'||!Number.isFinite(Date.parse(v)))reject('invalid');return new Date(v).toISOString();};
const https=v=>{if(!v)return '';try{const u=new URL(v);if(u.protocol!=='https:'||u.username||u.password)reject('invalid');return u.href;}catch{reject('invalid');}};
const isActive=a=>a.active&&Date.parse(a.starts)<=Date.now()&&(!a.ends||Date.parse(a.ends)>Date.now());
function person(users,id,role){if(!users.some(u=>u.id===id&&u.roles.includes(role)&&u.status!=='disabled'))reject('invalid_reference');return id;}
function course(d,id){if(!d.courses.some(c=>c.id===id))reject('invalid_reference');return id;}
function validate(kind,v,d,users,actor,existing){const common={id:existing?.id||crypto.randomUUID(),updated:new Date().toISOString()};
if(kind==='courses'){if(!Array.isArray(v.teacherIds)||!Array.isArray(v.lessons)||v.lessons.length>200)reject('invalid');return {...common,title:bilingual(v.title,true,200),description:bilingual(v.description),subject:text(v.subject,100,true),level:text(v.level,100,true),language:choice(v.language,['en','th','both']),status:choice(v.status,['draft','published','archived']),teacherIds:[...new Set(v.teacherIds.map(id=>person(users,id,'teacher')))],lessons:v.lessons.map((l,i)=>({id:existing?.lessons?.[i]?.id||crypto.randomUUID(),module:bilingual(l.module,true,200),title:bilingual(l.title,true,200),text:bilingual(l.text,false),videoUrl:https(l.videoUrl),materialUrl:https(l.materialUrl),minutes:number(l.minutes||0,0,600),preview:!!l.preview}))};}
if(kind==='assignments'){const starts=date(v.starts),ends=v.mode==='unlimited'?null:v.mode==='duration'?new Date(Date.parse(starts)+number(v.days,1,3650)*86400000).toISOString():date(v.ends);choice(v.mode,['fixed','duration','unlimited']);if(ends&&Date.parse(ends)<=Date.parse(starts))reject('invalid_date');if(d.assignments.some(a=>a.id!==common.id&&a.student===v.student&&a.course===v.course))reject('duplicate_assignment',409);return {...common,student:person(users,v.student,'student'),course:course(d,v.course),starts,ends,mode:v.mode,days:v.mode==='duration'?v.days:null,active:!!v.active};}
if(kind==='links'){if(v.verified!==true)reject('relationship_not_verified');if(d.links.some(l=>l.id!==common.id&&l.parent===v.parent&&l.student===v.student))reject('duplicate_link',409);return {...common,parent:person(users,v.parent,'parent'),student:person(users,v.student,'student'),verified:true,active:!!v.active,verifiedBy:actor.id,verificationNote:text(v.verificationNote,1000,true)};}
if(kind==='assessments'){if(!Array.isArray(v.questions)||!v.questions.length||v.questions.length>100)reject('invalid');return {...common,course:course(d,v.course),title:bilingual(v.title,true,200),type:choice(v.type,['placement','quiz','assignment','pre-test','post-test']),status:choice(v.status,['draft','published','archived']),passScore:number(v.passScore,0,100),attemptLimit:number(v.attemptLimit,1,20),releaseAnswers:!!v.releaseAnswers,questions:v.questions.map(q=>{const type=choice(q.type,['multiple','written']);return {type,prompt:bilingual(q.prompt),options:type==='multiple'?(Array.isArray(q.options)&&q.options.length===4?q.options.map(x=>bilingual(x,true,500)):reject('invalid')):[],answer:type==='multiple'?number(q.answer,0,3):null};})};}
if(kind==='events'){const start=date(v.start),deadline=date(v.deadline);if(Date.parse(deadline)>Date.parse(start))reject('invalid_date');return {...common,title:bilingual(v.title,true,200),description:bilingual(v.description),location:bilingual(v.location,true,300),start,deadline,capacity:number(v.capacity,1,10000),status:choice(v.status,['draft','published','archived'])};}
if(kind==='registrations'){const event=d.events.find(e=>e.id===v.event);if(!event)reject('invalid_reference');const status=choice(v.status,['confirmed','cancelled']);if(status==='confirmed'&&d.registrations.filter(r=>r.event===v.event&&r.status==='confirmed'&&r.id!==common.id).length>=event.capacity)reject('event_full',409);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.email||''))reject('invalid');return {...common,event:v.event,name:text(v.name,160,true),email:text(v.email,254,true).toLowerCase(),phone:text(v.phone||'',50),status};}
reject('invalid');}
export async function courseIdsFor(env,user){if(user.role!=='teacher')return [];const{doc}=await schoolRead(env);return doc.courses.filter(c=>c.teacherIds.includes(user.id)).map(c=>c.id);}
export async function schoolEndpoint(req,env,user,path,readBody){
if(path==='/api/catalog'&&req.method==='GET'){const{doc}=await schoolRead(env);return out({courses:doc.courses.filter(c=>c.status==='published').map(({lessons,teacherIds,...c})=>({...c,lessonCount:lessons.length,minutes:lessons.reduce((a,l)=>a+l.minutes,0)})),events:doc.events.filter(e=>e.status==='published').map(e=>({...e,registrations:doc.registrations.filter(r=>r.event===e.id&&r.status==='confirmed').length}))});}
if(path==='/api/event-register'&&req.method==='POST'){if(!user.id)reject('unauthorized',401);const data=await readBody(req);const r=await update(env,d=>{const e=d.events.find(e=>e.id===data.event&&e.status==='published');if(!e||Date.parse(e.deadline)<Date.now())reject('registration_closed',409);if(d.registrations.some(r=>r.event===e.id&&r.email===user.email&&r.status==='confirmed'))reject('already_registered',409);if(d.registrations.filter(r=>r.event===e.id&&r.status==='confirmed').length>=e.capacity)reject('event_full',409);const record={id:crypto.randomUUID(),event:e.id,name:user.name,email:user.email,phone:'',status:'confirmed',updated:new Date().toISOString()};d.registrations.push(record);return {id:record.id,status:'confirmed'};});return out(r.result,201);}
if(path==='/api/learning'&&req.method==='GET'){if(!user.id)reject('unauthorized',401);const{doc}=await schoolRead(env);const children=user.roles.includes('parent')?doc.links.filter(l=>l.parent===user.id&&l.verified&&l.active).map(l=>l.student):[];const studentIds=user.roles.includes('student')?[user.id,...children]:children;const teaching=user.roles.includes('teacher')?doc.courses.filter(c=>c.teacherIds.includes(user.id)).map(c=>c.id):[];const assignments=doc.assignments.filter(a=>studentIds.includes(a.student)||teaching.includes(a.course));const courseIds=assignments.filter(isActive).map(a=>a.course);return out({assignments,links:doc.links.filter(l=>l.parent===user.id&&l.verified&&l.active),courses:doc.courses.filter(c=>courseIds.includes(c.id)||teaching.includes(c.id)),assessments:doc.assessments.filter(a=>a.status==='published'&&courseIds.includes(a.course)).map(({questions,releaseAnswers,...a})=>({...a,questions:questions.map(({answer,...q})=>q)})),progress:doc.progress.filter(p=>studentIds.includes(p.student)||teaching.includes(p.course)),submissions:doc.submissions.filter(p=>studentIds.includes(p.student)||teaching.includes(p.course))});}
if(path==='/api/learning/complete'&&req.method==='POST'){if(!user.roles?.includes('student'))reject('forbidden',403);const data=await readBody(req);const r=await update(env,d=>{if(!d.assignments.some(a=>a.student===user.id&&a.course===data.course&&isActive(a)))reject('forbidden',403);const c=d.courses.find(c=>c.id===data.course);if(!c?.lessons.some(l=>l.id===data.lesson))reject('not_found',404);let p=d.progress.find(p=>p.student===user.id&&p.course===c.id&&p.lesson===data.lesson);if(!p){p={id:crypto.randomUUID(),student:user.id,course:c.id,lesson:data.lesson};d.progress.push(p);}p.completed=true;p.at=new Date().toISOString();return p;});return out(r.result);}
if(path==='/api/learning/submit'&&req.method==='POST'){if(!user.roles?.includes('student'))reject('forbidden',403);const data=await readBody(req);const r=await update(env,d=>{const a=d.assessments.find(a=>a.id===data.assessment&&a.status==='published');if(!a||!d.assignments.some(x=>x.student===user.id&&x.course===a.course&&isActive(x)))reject('forbidden',403);if(d.submissions.filter(s=>s.assessment===a.id&&s.student===user.id).length>=a.attemptLimit)reject('attempt_limit',409);if(!Array.isArray(data.answers)||data.answers.length!==a.questions.length)reject('invalid');let correct=0,manual=false;const answers=a.questions.map((q,i)=>{if(q.type==='multiple'){const value=number(data.answers[i],0,3);if(value===q.answer)correct++;return value;}manual=true;return text(data.answers[i],6000,true);});const score=manual?null:Math.round(100*correct/a.questions.length);const submission={id:crypto.randomUUID(),student:user.id,course:a.course,assessment:a.id,answers,score,passed:score===null?null:score>=a.passScore,feedback:'',at:new Date().toISOString(),status:manual?'pending':'graded'};d.submissions.push(submission);return {...submission,...(a.releaseAnswers?{releasedAnswers:a.questions.map(q=>q.answer)}:{})};});return out(r.result,201);}
if(path==='/api/admin/grade'&&req.method==='POST'){if(!user.roles?.includes('admin'))reject('forbidden',403);const data=await readBody(req);const r=await update(env,d=>{const s=d.submissions.find(s=>s.id===data.id),a=s&&d.assessments.find(a=>a.id===s.assessment);if(!s||!a)reject('not_found',404);s.score=number(data.score,0,100);s.feedback=text(data.feedback,6000,true);s.status='graded';s.passed=s.score>=a.passScore;s.gradedBy=user.id;return s;});return out(r.result);}
if(!path.startsWith('/api/admin/school'))return null;
if(!user.roles?.includes('admin'))reject('forbidden',403);
if(path==='/api/admin/school'&&req.method==='GET'){const{doc,etag}=await schoolRead(env);return out({...doc,etag});}
const match=path.match(/^\/api\/admin\/school\/(courses|assignments|links|assessments|events|registrations)(?:\/([a-f0-9-]{36}))?$/);if(!match)reject('not_found',404);
if(!['POST','PUT'].includes(req.method))reject('not_found',404);const data=await readBody(req),{doc:accounts}=await accountRead(env),kind=match[1],id=match[2];if(req.method==='PUT'&&!id||req.method==='POST'&&id)reject('invalid');
const result=await update(env,d=>{const existing=id?d[kind].find(v=>v.id===id):null;if(id&&!existing)reject('not_found',404);if(!existing&&d[kind].length>=10000)reject('limit',409);const record=validate(kind,data.record,d,accounts.users,user,existing);if(existing)d[kind][d[kind].indexOf(existing)]=record;else d[kind].push(record);return record;},data.etag);return out({record:result.result,etag:result.etag},id?200:201);
}
